# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T03:50:33+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel


class GetweatherGetResponse(BaseModel):
    City: Optional[str] = None
    Code: Optional[str] = None
    Credits: Optional[str] = None
    RelativeHumidity: Optional[str] = None
    State: Optional[str] = None
    TempC: Optional[str] = None
    TempF: Optional[str] = None
    VisibilityMiles: Optional[str] = None
    Weather: Optional[str] = None
    WindDir: Optional[str] = None
    WindMPH: Optional[str] = None
